name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

version-resolver:
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'bug'
      - 'chore'
      - 'documentation'
  default: patch

categories:
  - title: '🚀 Added'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Fixed'
    labels:
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
